/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/02/2016
 */
package me.aliyoo;

import me.aliyoo.controllers.*;
import me.aliyoo.http.client.HttpClient;

public class RealHereAPIClient {
    /**
     * Singleton access to User controller
     * @return	Returns the UserController instance 
     */
    public UserController getUser() {
        return UserController.getInstance();
    }

    /**
     * Singleton access to Conference controller
     * @return	Returns the ConferenceController instance 
     */
    public ConferenceController getConference() {
        return ConferenceController.getInstance();
    }

    /**
     * Singleton access to Sign controller
     * @return	Returns the SignController instance 
     */
    public SignController getSign() {
        return SignController.getInstance();
    }

    /**
     * Singleton access to Test controller
     * @return	Returns the TestController instance 
     */
    public TestController getTest() {
        return TestController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public RealHereAPIClient() { }
}