/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/10/2016
 */
package me.aliyoo.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConfcDataModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 4951529360892340495L;
    private String confcDetail = "X-待添加";
    private double confcDuration = 1.0;
    private int confcID = 111;
    private String confcLocation = "X-街道";
    private String confcOrger = "X-组织者";
    private Date confcTime;
    private String confcTitle = "X-大会";
    /** GETTER
     * 活动详细介绍，500字限制
     */
    @JsonGetter("confcDetail")
    public String getConfcDetail ( ) { 
        return this.confcDetail;
    }
    
    /** SETTER
     * 活动详细介绍，500字限制
     */
    @JsonSetter("confcDetail")
    public void setConfcDetail (String value) { 
        this.confcDetail = value;
        notifyObservers(this.confcDetail);
    }
 
    /** GETTER
     * 活动持续时间，单位（小时），默认为“1”
     */
    @JsonGetter("confcDuration")
    public double getConfcDuration ( ) { 
        return this.confcDuration;
    }
    
    /** SETTER
     * 活动持续时间，单位（小时），默认为“1”
     */
    @JsonSetter("confcDuration")
    public void setConfcDuration (double value) { 
        this.confcDuration = value;
        notifyObservers(this.confcDuration);
    }
 
    /** GETTER
     * 活动的唯一标识符
     */
    @JsonGetter("confcID")
    public int getConfcID ( ) { 
        return this.confcID;
    }
    
    /** SETTER
     * 活动的唯一标识符
     */
    @JsonSetter("confcID")
    public void setConfcID (int value) { 
        this.confcID = value;
        notifyObservers(this.confcID);
    }
 
    /** GETTER
     * 活动地址
     */
    @JsonGetter("confcLocation")
    public String getConfcLocation ( ) { 
        return this.confcLocation;
    }
    
    /** SETTER
     * 活动地址
     */
    @JsonSetter("confcLocation")
    public void setConfcLocation (String value) { 
        this.confcLocation = value;
        notifyObservers(this.confcLocation);
    }
 
    /** GETTER
     * 活动组织者
     */
    @JsonGetter("confcOrger")
    public String getConfcOrger ( ) { 
        return this.confcOrger;
    }
    
    /** SETTER
     * 活动组织者
     */
    @JsonSetter("confcOrger")
    public void setConfcOrger (String value) { 
        this.confcOrger = value;
        notifyObservers(this.confcOrger);
    }
 
    /** GETTER
     * 活动开始时间
     */
    @JsonGetter("confcTime")
    public Date getConfcTime ( ) { 
        return this.confcTime;
    }
    
    /** SETTER
     * 活动开始时间
     */
    @JsonSetter("confcTime")
    public void setConfcTime (Date value) { 
        this.confcTime = value;
        notifyObservers(this.confcTime);
    }
 
    /** GETTER
     * 活动标题
     */
    @JsonGetter("confcTitle")
    public String getConfcTitle ( ) { 
        return this.confcTitle;
    }
    
    /** SETTER
     * 活动标题
     */
    @JsonSetter("confcTitle")
    public void setConfcTitle (String value) { 
        this.confcTitle = value;
        notifyObservers(this.confcTitle);
    }
 
}
 