/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/10/2016
 */
package me.aliyoo.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConfcItemViewModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5636533289912470198L;
    private String confcLocation = "X-大堂";
    private String confcOrgerName = "X-组织者";
    private String confcStat = "正常开展中";
    private String confcTitle = "X-大会";
    /** GETTER
     * 活动地点
     */
    @JsonGetter("confcLocation")
    public String getConfcLocation ( ) { 
        return this.confcLocation;
    }
    
    /** SETTER
     * 活动地点
     */
    @JsonSetter("confcLocation")
    public void setConfcLocation (String value) { 
        this.confcLocation = value;
        notifyObservers(this.confcLocation);
    }
 
    /** GETTER
     * 组织者
     */
    @JsonGetter("confcOrgerName")
    public String getConfcOrgerName ( ) { 
        return this.confcOrgerName;
    }
    
    /** SETTER
     * 组织者
     */
    @JsonSetter("confcOrgerName")
    public void setConfcOrgerName (String value) { 
        this.confcOrgerName = value;
        notifyObservers(this.confcOrgerName);
    }
 
    /** GETTER
     * 会议状态
     */
    @JsonGetter("confcStat")
    public String getConfcStat ( ) { 
        return this.confcStat;
    }
    
    /** SETTER
     * 会议状态
     */
    @JsonSetter("confcStat")
    public void setConfcStat (String value) { 
        this.confcStat = value;
        notifyObservers(this.confcStat);
    }
 
    /** GETTER
     * 活动标题
     */
    @JsonGetter("confcTitle")
    public String getConfcTitle ( ) { 
        return this.confcTitle;
    }
    
    /** SETTER
     * 活动标题
     */
    @JsonSetter("confcTitle")
    public void setConfcTitle (String value) { 
        this.confcTitle = value;
        notifyObservers(this.confcTitle);
    }
 
}
 