/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 06/02/2016
 */
package me.aliyoo.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum LoginRoleEnum {
    VISITOR, //游客
    PARTER, //参与者
    ORGER; //组织者

    private static TreeMap<String, LoginRoleEnum> valueMap = new TreeMap<String, LoginRoleEnum>();
    private String value;

    static {
        VISITOR.value = "VISITOR";
        PARTER.value = "PARTER";
        ORGER.value = "ORGER";

        valueMap.put("VISITOR", VISITOR);
        valueMap.put("PARTER", PARTER);
        valueMap.put("ORGER", ORGER);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return	The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static LoginRoleEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return	The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }

    /**
     * Convert list of LoginRoleEnum values to list of string values
     * @param toConvert The list of LoginRoleEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<LoginRoleEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (LoginRoleEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 