/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/14/2016
 */
package me.aliyoo.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class TestRetDataModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5603832459480420196L;
    private String areaId;
    private String districtCn;
    private String nameCn;
    private String nameEn;
    private String provinceCn;
    /** GETTER
     * 城市代码
     */
    @JsonGetter("area_id")
    public String getAreaId ( ) { 
        return this.areaId;
    }
    
    /** SETTER
     * 城市代码
     */
    @JsonSetter("area_id")
    public void setAreaId (String value) { 
        this.areaId = value;
        notifyObservers(this.areaId);
    }
 
    /** GETTER
     * 市级
     */
    @JsonGetter("district_cn")
    public String getDistrictCn ( ) { 
        return this.districtCn;
    }
    
    /** SETTER
     * 市级
     */
    @JsonSetter("district_cn")
    public void setDistrictCn (String value) { 
        this.districtCn = value;
        notifyObservers(this.districtCn);
    }
 
    /** GETTER
     * 区县中文
     */
    @JsonGetter("name_cn")
    public String getNameCn ( ) { 
        return this.nameCn;
    }
    
    /** SETTER
     * 区县中文
     */
    @JsonSetter("name_cn")
    public void setNameCn (String value) { 
        this.nameCn = value;
        notifyObservers(this.nameCn);
    }
 
    /** GETTER
     * 城市拼音
     */
    @JsonGetter("name_en")
    public String getNameEn ( ) { 
        return this.nameEn;
    }
    
    /** SETTER
     * 城市拼音
     */
    @JsonSetter("name_en")
    public void setNameEn (String value) { 
        this.nameEn = value;
        notifyObservers(this.nameEn);
    }
 
    /** GETTER
     * 省级
     */
    @JsonGetter("province_cn")
    public String getProvinceCn ( ) { 
        return this.provinceCn;
    }
    
    /** SETTER
     * 省级
     */
    @JsonSetter("province_cn")
    public void setProvinceCn (String value) { 
        this.provinceCn = value;
        notifyObservers(this.provinceCn);
    }
 
}
 