/*
 * RealHereAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/10/2016
 */
package me.aliyoo.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class UaerItemViewModel 
        extends java.util.Observable
        implements java.io.Serializable {
    private static final long serialVersionUID = 5101462485851316446L;
    private String email = "example@123.com";
    private String userCom = "X-Company";
    private String userName = "X-Man";
    /** GETTER
     * 用户邮箱
     */
    @JsonGetter("email")
    public String getEmail ( ) { 
        return this.email;
    }
    
    /** SETTER
     * 用户邮箱
     */
    @JsonSetter("email")
    public void setEmail (String value) { 
        this.email = value;
        notifyObservers(this.email);
    }
 
    /** GETTER
     * 用户所属组织
     */
    @JsonGetter("userCom")
    public String getUserCom ( ) { 
        return this.userCom;
    }
    
    /** SETTER
     * 用户所属组织
     */
    @JsonSetter("userCom")
    public void setUserCom (String value) { 
        this.userCom = value;
        notifyObservers(this.userCom);
    }
 
    /** GETTER
     * 用户名
     */
    @JsonGetter("userName")
    public String getUserName ( ) { 
        return this.userName;
    }
    
    /** SETTER
     * 用户名
     */
    @JsonSetter("userName")
    public void setUserName (String value) { 
        this.userName = value;
        notifyObservers(this.userName);
    }
 
}
 